apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elastic
spec:
  containers:
  - name: fluentd-elastic
    image: docker.io/falkonry/fluentd-elastic:docker
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: "ELASTIC_HOST"
      value: "hostname"
    - name: "ELASTIC_PORT"
      value: "port"
    - name: "ELASTIC_INDEX"
      value: "docker"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: containers
      mountPath: /var/lib/docker/containers
      readOnly: true
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
